
package training.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Mon Jun 22 17:03:53 SGT 2015
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "HelloWorldResponse", namespace = "http://training/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HelloWorldResponse", namespace = "http://training/")

public class HelloWorldResponse {

    @XmlElement(name = "return")
    private training.Customer _return;

    public training.Customer getReturn() {
        return this._return;
    }

    public void setReturn(training.Customer new_return)  {
        this._return = new_return;
    }

}

