
package training.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Mon Jun 22 17:03:53 SGT 2015
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "HelloWorld", namespace = "http://training/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HelloWorld", namespace = "http://training/")

public class HelloWorld {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

